version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: another/package
  system_packages: true

#formats:
#    - pdf

sphinx:
  fail_on_warning: true
