[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "metabarcoding@cefas"
authors = [{name = "Nicola Coyle", email = "nicola.coyle@cefas.co.uk"}]
dynamic = ["1.0", "Metabarcoding at Cefas"]
