##======================================================##
##
## Testing the microbiome R package
##
## Resource: https://microbiome.github.io/tutorials/
##
## Author: Nicola Coyle
## Date: 17/03/022
##
##======================================================##

#================================================#
# Install libraries 
#================================================#

# Install microbiome
library(BiocManager)
BiocManager::install("microbiome")

# Install microbiomeutilities
install.packages("devtools")
devtools::install_github("microsud/microbiomeutilities")

# load libraries
library(microbiome) 
library(microbiomeutilities) 

#================================================#
# Importing standard formats (CSV, Mothur, BIOM)
#================================================#

# Import output CSV files generated by write_phyloseq
pseq1 <- read_phyloseq(otu.file, taxonomy.file, metadata.file, type = "simple")

# Import mother .shared and .taxonomy and metadata files
pseq2 <- read_phyloseq(otu.file, taxonomy.file, metadata.file, type = "mothur")

# Import BIOM files
pseq3 <- read_phyloseq(otu.file, taxonomy.file, metadata.file, type = "biom")

# Alternatively, you can read your data in R (read.table, read.csv or other standard functions) and convert into phyloseq format.
# http://joey711.github.io/phyloseq/import-data

#================================================#
# Some Test data:
#================================================#

# Data citation doi: 10.1038/ncomms5344
data(atlas1006) 
print(atlas1006)

# Data citation doi: 10.1038/ncomms7342
data(dietswap)
print(dietswap)

# Data citation doi: 10.7717/peerj.32
data(peerj32)
print(names(peerj32))

#================================================#
# initial look
#================================================#

# https://microbiome.github.io/tutorials/Preprocessing.html

data(atlas1006)   
# Rename the example data (which is a phyloseq object)
pseq <- atlas1006

summarize_phyloseq(pseq)

# metadata extract 
meta <- meta(pseq)

# taxtable extract
taxonomy <- tax_table(pseq)

# Absolute abundances
otu.absolute <- abundances(pseq)
otu.absolute[1:5,1:5]

# Relative abundances
otu.relative <- abundances(pseq, "compositional")
otu.relative[1:5,1:5]

#Total read counts:
reads_sample <- readcount(pseq)
# check for first 5 samples
reads_sample[1:5]

# Add read per sample to phyloseq object metadata.
sample_data(pseq)$reads_sample <- reads_sample

# reads_sample is add to the last column in sample_data of pseq object.
head(meta(pseq)[,c("sample", "reads_sample")])

# melt for plotting
df <- psmelt(pseq)
kable(head(df))

# sample sums function - how many OTU per sample
s <- sample_sums(pseq)

# look for specific taxa  
head(abundances(pseq)["Akkermansia",])
abundances(pseq)[1:10,1:10]

# subset
pseq.subset <- subset_samples(pseq, nationality == "AFR")

# pseq
sample_variables(pseq)

# get values for first variable 
head(get_variable(pseq, sample_variables(pseq)[1]))

# Calculate diversity for samples
div <- microbiome::alpha(pseq, index = "shannon")

# Assign the estimated diversity to sample metadata
sample_data(pseq)$diversity <- div

#Taxa operations
#Number of taxa
n <- ntaxa(pseq)

#Most abundant taxa
topx <- top_taxa(pseq, n = 10)

#Names
ranks <- rank_names(pseq)  # Taxonomic levels
taxa  <- taxa(pseq)        # Taxa names at the analysed level

#Subset taxa
pseq.bac <- subset_taxa(pseq, Phylum == "Bacteroidetes")
#Prune (select) taxa:
  
# List of Genera in the Bacteroideted Phylum
taxa <- map_levels(NULL, "Phylum", "Genus", pseq)$Bacteroidetes

# With given taxon names
ex2 <- prune_taxa(taxa, pseq)

# Taxa with positive sum across samples
ex3 <- prune_taxa(taxa_sums(pseq) > 0, pseq)

#Filter by user-specified function values (here variance):
f <- filter_taxa(pseq, function(x) var(x) > 1e-05, TRUE)

#List unique phylum-level groups:
head(get_taxa_unique(pseq, "Phylum"))

## [1] "Actinobacteria"  "Firmicutes"      "Proteobacteria"  "Verrucomicrobia" "Bacteroidetes"   "Spirochaetes"
#Pick the taxa abundances for a given sample:
samplename <- sample_names(pseq)[[1]]

# Pick abundances for a particular taxon
tax.abundances <- abundances(pseq)[, samplename]

#================================================#
# fix dada2 ASV names
#================================================#

ps <- add_refseq(ps, tag = "ASV") # tag option converts the sequence to an ID
# check again
taxa_names(ps)[1:2]

ps <- microbiome::add_besthit(ps)
taxa_names(ps)[1:2]

# 
pseq.rarified <- rarefy_even_depth(pseq)

#==
# change meta
#==
# Example data
data(dietswap)
pseq <- dietswap

# Pick the existing metadata from a phyloseq object
# (or retrieve this from another source)
df <- meta(pseq)

# Merge the metadata back in the phyloseq object
pseq2 <- merge_phyloseq(pseq, sample_data(df))

#================================================#
# data cleaning
#================================================#

# load data: 
ps <- zackular2014

# summarise data
microbiome::summarize_phyloseq(ps)

# OTU table  
otu_tab <- microbiome::abundances(ps)
# check 
otu_tab[1:5,1:5] # for my table show me [1 to 5 rows, 1 to 5 columns]

# Taxonomy table
tax_tab <- phyloseq::tax_table(ps)
# check 
tax_tab[1:5,1:5] # for my table show me [1 to 5 otu ids, 1 to 5 first five ranks]

# accessing the OTUids 
taxa_names(ps)[1:5] # print first 5 ids

# find and substitute
taxa_names(ps) <- gsub(taxa_names(ps), pattern = "d__", replacement = "")  

# Check again Taxonomy table
phyloseq::tax_table(ps)[1:3,1:3] # check for my table show me [1 to 3 otu ids, 1 to 3 first three ranks].

# find and substitute
taxa_names(ps) <- gsub(taxa_names(ps), pattern = "denovo", replacement = "OTU-")  

# extending gsub to entire table 
tax_table(ps)[, colnames(tax_table(ps))] <- gsub(tax_table(ps)[, colnames(tax_table(ps))],     pattern = "[a-z]__", replacement = "")

colnames(tax_table(ps))

# Replace sequence IDs with ATACAACTATACG with ASV1 and so on...
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))


# remove asterisk
tax_table(ps)[,colnames(tax_table(ps))] <- gsub(tax_table(ps)[,colnames(tax_table(ps))],pattern="[*]",replacement="") # notice here the square brackets. These are required when special characters such as * and ~ below are used as they have functional role in R base programming. 

# remove ~
tax_table(ps)[,colnames(tax_table(ps))] <- gsub(tax_table(ps)[,colnames(tax_table(ps))],pattern="[~]",replacement="")

# For each column separately we attempt to replace "k__<empty>" with "" for consistency.
tax_table(ps)[tax_table(ps) == "k__<empty>"] <- ""
tax_table(ps)[tax_table(ps) == "p__<empty>"] <- ""
tax_table(ps)[tax_table(ps) == "c__<empty>"] <- ""
tax_table(ps)[tax_table(ps) == "o__<empty>"] <- ""
tax_table(ps)[tax_table(ps) == "f__<empty>"] <- ""
tax_table(ps)[tax_table(ps) == "g__<empty>"] <- ""
# some more ambiguities 
tax_table(ps)[tax_table(ps) == "o__Unknown_Order"] <- ""
tax_table(ps)[tax_table(ps) == "c__Unknown_Class"] <- ""
tax_table(ps)[tax_table(ps) == "f__Unknown_Family"] <- ""

# aggregate at genus level
ps.gen <- phyloseq::tax_glom(ps, "Genus", NArm = TRUE)

# look at genus
unique(tax_table(ps.gen)[,"Genus"] )

# change neames with spces to underline
taxa_names(ps) <- gsub(" ", ".", taxa_names(ps))

# change [name] to name
taxa_names(ps) <- gsub("\\[|\\]", "", taxa_names(ps))

# change - to . 
taxa_names(ps) <- gsub("-", ".", taxa_names(ps))

# 










